-- MySQL Script generated by MySQL Workbench
-- Thu May 13 21:33:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema batallas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `batallas` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `batallas` DEFAULT CHARACTER SET utf8 ;
USE `batallas` ;

-- -----------------------------------------------------
-- Table `mydb`.`race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`race` ;

CREATE TABLE IF NOT EXISTS `batallas`.`race` (
  `race_id` INT NOT NULL,
  `race_name` VARCHAR(200) NULL,
  `hp` INT NULL,
  `strength` INT NULL,
  `speed` INT NULL,
  `agility` INT NULL,
  `defense` INT NULL,
  PRIMARY KEY (`race_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batallas`.`warriors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`warriors` ;

CREATE TABLE IF NOT EXISTS `batallas`.`warriors` (
  `warrior_id` INT NOT NULL,
  `warrior_name` VARCHAR(200) NULL,
  `warrior_image_path` VARCHAR(200) NULL,
  `race_id` INT NULL,
  PRIMARY KEY (`warrior_id`),
  INDEX `race_id_idx` (`race_id` ASC) VISIBLE,
  CONSTRAINT `race_id`
    FOREIGN KEY (`race_id`)
    REFERENCES `batallas`.`race` (`race_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batallas`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`players` ;

CREATE TABLE IF NOT EXISTS `batallas`.`players` (
  `player_id` INT NOT NULL,
  `player_name` VARCHAR(200) NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batallas`.`ranking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`ranking` ;

CREATE TABLE IF NOT EXISTS `batallas`.`ranking` (
  `player_id` INT NULL,
  `total_points` INT NULL,
  `warrior_id` INT NULL,
  INDEX `player_id_idx` (`player_id` ASC) VISIBLE,
  INDEX `warrior_id_idx` (`warrior_id` ASC) VISIBLE,
  CONSTRAINT `player_id`
    FOREIGN KEY (`player_id`)
    REFERENCES `batallas`.`players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `warrior_id`
    FOREIGN KEY (`warrior_id`)
    REFERENCES `batallas`.`warriors` (`warrior_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batallas`.`weapons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`weapons` ;

CREATE TABLE IF NOT EXISTS `batallas`.`weapons` (
  `weapon_id` INT NOT NULL,
  `weapon_name` VARCHAR(200) NULL,
  `weapon_image_path` VARCHAR(200) NULL,
  `strength` INT NULL,
  `speed` INT NULL,
  `weapon_race` VARCHAR(200) NULL,
  PRIMARY KEY (`weapon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `batallas`.`battles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batallas`.`battles` ;

CREATE TABLE IF NOT EXISTS `batallas`.`battles` (
  `battle_id` INT NOT NULL,
  `player_id` INT NULL,
  `warrior_id` INT NULL,
  `weapon_id` INT NULL,
  `opponent_id` INT NULL,
  `opponent_weapon_id` INT NULL,
  `injuries_caused` INT NULL,
  `injuries_suffered` INT NULL,
  `battle_points` INT NULL,
  PRIMARY KEY (`battle_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
